name: format validation
run-name: ${{ github.actor }} is validating actoins 🚀
on: [push]
jobs:
  format_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: install ruff
        run: pip install ruff
      - name: lint
        run: ruff check -v

      - name: format
        run: ruff format -v